language: c

install:
    - sudo apt-get update
    - sudo apt-get install libc6-dev-i386 gcc-multilib

matrix:
  include:
    - env: TASK="make test" COMPILER=gcc ARCH=32bit
      compiler:
        - gcc
    - env: TASK="make test" COMPILER=gcc ARCH=64bit
      compiler:
        - gcc
    - env: TASK="make test" COMPILER=clang ARCH=32bit
      compiler:
        - clang
    - env: TASK="make test" COMPILER=clang ARCH=64bit
      compiler:
        - clang

    - env: TASK="make emscripten" COMPILER=emcc
      language: node_js
      node_js:
        - node
      sudo: required
      services:
        - docker
      before_install:
        - docker run -e PWD=/src -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
      script:
        - docker exec -it emscripten make emscripten
        - ./som-em.sh -cp Smalltalk TestSuite/TestHarness.som

script:
    - export CC=${COMPILER} # hack around a Travis issue
    - ${TASK}
