stages:
  - build-test-benchmark

variables:
  PYTHONUNBUFFERED: "true"

before_script:
  - git submodule update --init

build_test_benchmark_job:
  stage: build-test-benchmark
  tags: [benchmarks, infinity]
  script:
    - ARCH=64bit make
    - ARCH=64bit make test
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf CSOM
